# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elio_gui_3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main_window(object):
    def setupUi(self, Main_window):
        Main_window.setObjectName("Main_window")
        Main_window.resize(1124, 841)
        self.centralwidget = QtWidgets.QWidget(Main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_opt1_titol = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_opt1_titol.setFont(font)
        self.label_opt1_titol.setAlignment(QtCore.Qt.AlignCenter)
        self.label_opt1_titol.setObjectName("label_opt1_titol")
        self.verticalLayout.addWidget(self.label_opt1_titol)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_op1_105 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_105.setFont(font)
        self.label_op1_105.setObjectName("label_op1_105")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_op1_105)
        self.lineEdit_EPU105 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_EPU105.setFont(font)
        self.lineEdit_EPU105.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_EPU105.setObjectName("lineEdit_EPU105")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_EPU105)
        self.label_op1_57 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_57.setFont(font)
        self.label_op1_57.setObjectName("label_op1_57")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_op1_57)
        self.lineEdit_EPU57 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_EPU57.setFont(font)
        self.lineEdit_EPU57.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_EPU57.setObjectName("lineEdit_EPU57")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_EPU57)
        self.label_op1_63 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_63.setFont(font)
        self.label_op1_63.setText("")
        self.label_op1_63.setObjectName("label_op1_63")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_op1_63)
        self.lineEdit_EPU57_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EPU57_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_EPU57_2.setFont(font)
        self.lineEdit_EPU57_2.setText("")
        self.lineEdit_EPU57_2.setFrame(False)
        self.lineEdit_EPU57_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_EPU57_2.setObjectName("lineEdit_EPU57_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_EPU57_2)
        self.label_op1_64 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_64.setFont(font)
        self.label_op1_64.setText("")
        self.label_op1_64.setObjectName("label_op1_64")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_op1_64)
        self.lineEdit_EPU57_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EPU57_3.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_EPU57_3.setFont(font)
        self.lineEdit_EPU57_3.setText("")
        self.lineEdit_EPU57_3.setFrame(False)
        self.lineEdit_EPU57_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_EPU57_3.setObjectName("lineEdit_EPU57_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_EPU57_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_opt1_titol_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_opt1_titol_2.setFont(font)
        self.label_opt1_titol_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_opt1_titol_2.setObjectName("label_opt1_titol_2")
        self.verticalLayout_3.addWidget(self.label_opt1_titol_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_op1_106 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_106.setFont(font)
        self.label_op1_106.setObjectName("label_op1_106")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_op1_106)
        self.lineEdit_FE_Hgap = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_FE_Hgap.setFont(font)
        self.lineEdit_FE_Hgap.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FE_Hgap.setObjectName("lineEdit_FE_Hgap")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_FE_Hgap)
        self.label_op1_58 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_58.setFont(font)
        self.label_op1_58.setObjectName("label_op1_58")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_op1_58)
        self.lineEdit_FE_Hctr = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_FE_Hctr.setFont(font)
        self.lineEdit_FE_Hctr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FE_Hctr.setObjectName("lineEdit_FE_Hctr")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_FE_Hctr)
        self.label_op1_59 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_59.setFont(font)
        self.label_op1_59.setObjectName("label_op1_59")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_op1_59)
        self.lineEdit_FE_Vgap = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_FE_Vgap.setFont(font)
        self.lineEdit_FE_Vgap.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FE_Vgap.setObjectName("lineEdit_FE_Vgap")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_FE_Vgap)
        self.label_op1_60 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_60.setFont(font)
        self.label_op1_60.setObjectName("label_op1_60")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_op1_60)
        self.lineEdit_FE_Vctr = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_FE_Vctr.setFont(font)
        self.lineEdit_FE_Vctr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FE_Vctr.setObjectName("lineEdit_FE_Vctr")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_FE_Vctr)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_opt1_titol_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_opt1_titol_3.setFont(font)
        self.label_opt1_titol_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_opt1_titol_3.setObjectName("label_opt1_titol_3")
        self.verticalLayout_2.addWidget(self.label_opt1_titol_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_op1_107 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_107.setFont(font)
        self.label_op1_107.setObjectName("label_op1_107")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_op1_107)
        self.lineEdit_M1_x = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_M1_x.setFont(font)
        self.lineEdit_M1_x.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_M1_x.setObjectName("lineEdit_M1_x")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_M1_x)
        self.label_op1_61 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_61.setFont(font)
        self.label_op1_61.setObjectName("label_op1_61")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_op1_61)
        self.lineEdit_M1_Ry = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_M1_Ry.setFont(font)
        self.lineEdit_M1_Ry.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_M1_Ry.setObjectName("lineEdit_M1_Ry")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_M1_Ry)
        self.label_op1_62 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_62.setFont(font)
        self.label_op1_62.setObjectName("label_op1_62")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_op1_62)
        self.lineEdit_M1_Rz = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_M1_Rz.setFont(font)
        self.lineEdit_M1_Rz.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_M1_Rz.setObjectName("lineEdit_M1_Rz")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_M1_Rz)
        self.label_op1_65 = QtWidgets.QLabel(self.centralwidget)
        self.label_op1_65.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_op1_65.setFont(font)
        self.label_op1_65.setText("")
        self.label_op1_65.setObjectName("label_op1_65")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_op1_65)
        self.lineEdit_M1_Rz_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_M1_Rz_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_M1_Rz_2.setFont(font)
        self.lineEdit_M1_Rz_2.setText("")
        self.lineEdit_M1_Rz_2.setFrame(False)
        self.lineEdit_M1_Rz_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_M1_Rz_2.setObjectName("lineEdit_M1_Rz_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_M1_Rz_2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 8)
        spacerItem4 = QtWidgets.QSpacerItem(20, 292, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 292, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 1, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 292, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 1, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 292, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 1, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 292, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 1, 6, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 292, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 1, 7, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 292, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 739, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 0, 2, 2, 1)
        spacerItem12 = QtWidgets.QSpacerItem(195, 32, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scan_lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.scan_lbl.setFont(font)
        self.scan_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.scan_lbl.setObjectName("scan_lbl")
        self.gridLayout.addWidget(self.scan_lbl, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 147, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 0, 1, 5, 1)
        self.start_lbl_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.start_lbl_3.setFont(font)
        self.start_lbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.start_lbl_3.setObjectName("start_lbl_3")
        self.gridLayout.addWidget(self.start_lbl_3, 0, 2, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 157, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem14, 0, 4, 5, 2)
        self.start_lbl_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.start_lbl_4.setFont(font)
        self.start_lbl_4.setAlignment(QtCore.Qt.AlignCenter)
        self.start_lbl_4.setObjectName("start_lbl_4")
        self.gridLayout.addWidget(self.start_lbl_4, 0, 6, 1, 2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem15, 0, 8, 4, 1)
        self.start_lbl_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.start_lbl_5.setFont(font)
        self.start_lbl_5.setAlignment(QtCore.Qt.AlignCenter)
        self.start_lbl_5.setObjectName("start_lbl_5")
        self.gridLayout.addWidget(self.start_lbl_5, 0, 9, 1, 2)
        self.comboBox_scan = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_scan.setObjectName("comboBox_scan")
        self.gridLayout.addWidget(self.comboBox_scan, 1, 0, 1, 1)
        self.comboBox_motor = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_motor.setObjectName("comboBox_motor")
        self.gridLayout.addWidget(self.comboBox_motor, 1, 5, 1, 3)
        self.comboBox_detector = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_detector.setObjectName("comboBox_detector")
        self.gridLayout.addWidget(self.comboBox_detector, 1, 2, 1, 2)
        self.comboBox_ch = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ch.setObjectName("comboBox_ch")
        self.comboBox_ch.addItem("")
        self.comboBox_ch.addItem("")
        self.comboBox_ch.addItem("")
        self.comboBox_ch.addItem("")
        self.gridLayout.addWidget(self.comboBox_ch, 2, 3, 1, 1)
        self.comboBox_motor_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_motor_2.setEnabled(False)
        self.comboBox_motor_2.setObjectName("comboBox_motor_2")
        self.gridLayout.addWidget(self.comboBox_motor_2, 1, 9, 1, 2)
        spacerItem16 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 1, 11, 1, 1)
        self.ch_lbl = QtWidgets.QLabel(self.centralwidget)
        self.ch_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ch_lbl.setObjectName("ch_lbl")
        self.gridLayout.addWidget(self.ch_lbl, 2, 2, 1, 1)
        self.start_lbl = QtWidgets.QLabel(self.centralwidget)
        self.start_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.start_lbl.setObjectName("start_lbl")
        self.gridLayout.addWidget(self.start_lbl, 2, 6, 1, 1)
        self.lineEdit_start = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_start.setObjectName("lineEdit_start")
        self.gridLayout.addWidget(self.lineEdit_start, 2, 7, 1, 1)
        self.start_lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.start_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.start_lbl_2.setObjectName("start_lbl_2")
        self.gridLayout.addWidget(self.start_lbl_2, 2, 9, 1, 1)
        self.lineEdit_start_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_start_2.setEnabled(False)
        self.lineEdit_start_2.setObjectName("lineEdit_start_2")
        self.gridLayout.addWidget(self.lineEdit_start_2, 2, 10, 1, 1)
        self.stop_lbl = QtWidgets.QLabel(self.centralwidget)
        self.stop_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_lbl.setObjectName("stop_lbl")
        self.gridLayout.addWidget(self.stop_lbl, 3, 6, 1, 1)
        self.lineEdit_stop = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_stop.setObjectName("lineEdit_stop")
        self.gridLayout.addWidget(self.lineEdit_stop, 3, 7, 1, 1)
        self.stop_lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.stop_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_lbl_2.setObjectName("stop_lbl_2")
        self.gridLayout.addWidget(self.stop_lbl_2, 3, 9, 1, 1)
        self.lineEdit_stop_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_stop_2.setEnabled(False)
        self.lineEdit_stop_2.setObjectName("lineEdit_stop_2")
        self.gridLayout.addWidget(self.lineEdit_stop_2, 3, 10, 1, 1)
        self.step_lbl = QtWidgets.QLabel(self.centralwidget)
        self.step_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.step_lbl.setObjectName("step_lbl")
        self.gridLayout.addWidget(self.step_lbl, 4, 6, 1, 1)
        self.lineEdit_step = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_step.setObjectName("lineEdit_step")
        self.gridLayout.addWidget(self.lineEdit_step, 4, 7, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 4, 8, 2, 1)
        self.step_lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.step_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.step_lbl_2.setObjectName("step_lbl_2")
        self.gridLayout.addWidget(self.step_lbl_2, 4, 9, 1, 1)
        self.lineEdit_step_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_step_2.setEnabled(False)
        self.lineEdit_step_2.setObjectName("lineEdit_step_2")
        self.gridLayout.addWidget(self.lineEdit_step_2, 4, 10, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 5, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 5, 4, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(588, 33, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 6, 0, 1, 11)
        self.checkBox_re = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_re.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_re.setObjectName("checkBox_re")
        self.gridLayout.addWidget(self.checkBox_re, 3, 11, 1, 1)
        self.pushButton_startscan = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_startscan.setFont(font)
        self.pushButton_startscan.setObjectName("pushButton_startscan")
        self.gridLayout.addWidget(self.pushButton_startscan, 6, 11, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(585, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 7, 0, 1, 1)
        self.pushButton_abort = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier [ibm]")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_abort.setFont(font)
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.gridLayout.addWidget(self.pushButton_abort, 7, 11, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(1017, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem22, 2, 0, 1, 2)
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier [ibm]")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.gridLayout_3.addWidget(self.pushButton_quit, 2, 2, 1, 1)
        Main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuStatus = QtWidgets.QMenu(self.menubar)
        self.menuStatus.setObjectName("menuStatus")
        Main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main_window)
        self.statusbar.setObjectName("statusbar")
        Main_window.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(Main_window)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Main_window)
        self.actionSave.setObjectName("actionSave")
        self.actionDisplay = QtWidgets.QAction(Main_window)
        self.actionDisplay.setObjectName("actionDisplay")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuStatus.addAction(self.actionDisplay)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuStatus.menuAction())
        self.label_op1_105.setBuddy(self.lineEdit_EPU105)
        self.label_op1_57.setBuddy(self.lineEdit_EPU57)
        self.label_op1_63.setBuddy(self.lineEdit_EPU57)
        self.label_op1_64.setBuddy(self.lineEdit_EPU57)
        self.label_op1_106.setBuddy(self.lineEdit_FE_Hgap)
        self.label_op1_58.setBuddy(self.lineEdit_FE_Hctr)
        self.label_op1_59.setBuddy(self.lineEdit_FE_Vgap)
        self.label_op1_60.setBuddy(self.lineEdit_FE_Vctr)
        self.label_op1_107.setBuddy(self.lineEdit_M1_x)
        self.label_op1_61.setBuddy(self.lineEdit_M1_Ry)
        self.label_op1_62.setBuddy(self.lineEdit_M1_Rz)
        self.label_op1_65.setBuddy(self.lineEdit_M1_Rz)

        self.retranslateUi(Main_window)
        QtCore.QMetaObject.connectSlotsByName(Main_window)

    def retranslateUi(self, Main_window):
        _translate = QtCore.QCoreApplication.translate
        Main_window.setWindowTitle(_translate("Main_window", "MainWindow"))
        self.label_opt1_titol.setText(_translate("Main_window", "EPU"))
        self.label_op1_105.setText(_translate("Main_window", "EPU105"))
        self.lineEdit_EPU105.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_EPU105.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_EPU105.setText(_translate("Main_window", "gap, phase"))
        self.label_op1_57.setText(_translate("Main_window", "EPU57"))
        self.lineEdit_EPU57.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_EPU57.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_EPU57.setText(_translate("Main_window", "gap, phase"))
        self.lineEdit_EPU57_2.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_EPU57_2.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_EPU57_3.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_EPU57_3.setWhatsThis(_translate("Main_window", "first optic title"))
        self.label_opt1_titol_2.setText(_translate("Main_window", "FE Slits"))
        self.label_op1_106.setText(_translate("Main_window", "H_GAP"))
        self.lineEdit_FE_Hgap.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_FE_Hgap.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_FE_Hgap.setText(_translate("Main_window", "h_gap"))
        self.label_op1_58.setText(_translate("Main_window", "H_CTR"))
        self.lineEdit_FE_Hctr.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_FE_Hctr.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_FE_Hctr.setText(_translate("Main_window", "h_center"))
        self.label_op1_59.setText(_translate("Main_window", "V_GAP"))
        self.lineEdit_FE_Vgap.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_FE_Vgap.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_FE_Vgap.setText(_translate("Main_window", "v_gap"))
        self.label_op1_60.setText(_translate("Main_window", "V_CTR"))
        self.lineEdit_FE_Vctr.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_FE_Vctr.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_FE_Vctr.setText(_translate("Main_window", "v_center"))
        self.label_opt1_titol_3.setText(_translate("Main_window", "M1"))
        self.label_op1_107.setText(_translate("Main_window", "x_inout"))
        self.lineEdit_M1_x.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_M1_x.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_M1_x.setText(_translate("Main_window", "h_gap"))
        self.label_op1_61.setText(_translate("Main_window", "Ry_pitch"))
        self.lineEdit_M1_Ry.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_M1_Ry.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_M1_Ry.setText(_translate("Main_window", "h_center"))
        self.label_op1_62.setText(_translate("Main_window", "Rz_roll"))
        self.lineEdit_M1_Rz.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_M1_Rz.setWhatsThis(_translate("Main_window", "first optic title"))
        self.lineEdit_M1_Rz.setText(_translate("Main_window", "v_gap"))
        self.lineEdit_M1_Rz_2.setStatusTip(_translate("Main_window", "optic 1"))
        self.lineEdit_M1_Rz_2.setWhatsThis(_translate("Main_window", "first optic title"))
        self.scan_lbl.setText(_translate("Main_window", "scan"))
        self.start_lbl_3.setText(_translate("Main_window", "detector"))
        self.start_lbl_4.setText(_translate("Main_window", "motor"))
        self.start_lbl_5.setText(_translate("Main_window", "inner motor"))
        self.comboBox_ch.setItemText(0, _translate("Main_window", "1"))
        self.comboBox_ch.setItemText(1, _translate("Main_window", "2"))
        self.comboBox_ch.setItemText(2, _translate("Main_window", "3"))
        self.comboBox_ch.setItemText(3, _translate("Main_window", "4"))
        self.ch_lbl.setText(_translate("Main_window", "ch."))
        self.start_lbl.setText(_translate("Main_window", "start"))
        self.lineEdit_start.setText(_translate("Main_window", "10"))
        self.start_lbl_2.setText(_translate("Main_window", "start"))
        self.lineEdit_start_2.setText(_translate("Main_window", "20"))
        self.stop_lbl.setText(_translate("Main_window", "stop"))
        self.lineEdit_stop.setText(_translate("Main_window", "20"))
        self.stop_lbl_2.setText(_translate("Main_window", "stop"))
        self.lineEdit_stop_2.setText(_translate("Main_window", "25"))
        self.step_lbl.setText(_translate("Main_window", "step"))
        self.lineEdit_step.setText(_translate("Main_window", "1"))
        self.step_lbl_2.setText(_translate("Main_window", "step"))
        self.lineEdit_step_2.setText(_translate("Main_window", ".5"))
        self.checkBox_re.setStatusTip(_translate("Main_window", "run engine option"))
        self.checkBox_re.setWhatsThis(_translate("Main_window", "select run engine"))
        self.checkBox_re.setText(_translate("Main_window", "RE"))
        self.pushButton_startscan.setText(_translate("Main_window", "Start Scan"))
        self.pushButton_abort.setText(_translate("Main_window", "Abort"))
        self.pushButton_quit.setText(_translate("Main_window", "Quit"))
        self.menuFile.setTitle(_translate("Main_window", "File"))
        self.menuStatus.setTitle(_translate("Main_window", "Status"))
        self.actionOpen.setText(_translate("Main_window", "Open"))
        self.actionSave.setText(_translate("Main_window", "Save"))
        self.actionDisplay.setText(_translate("Main_window", "display"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_window = QtWidgets.QMainWindow()
    ui = Ui_Main_window()
    ui.setupUi(Main_window)
    Main_window.show()
    sys.exit(app.exec_())

